name: vgg_hgru
import_prepath: models.vgg_16
import_class: VGG_16
args:
  weight_path: /media/data_cifs/aimen/CC_experiments/model_weights/vgg_16.pth.tar
  load_weights: true 
  freeze_layers: true
  n_layers: 17